### ISSUE TITLE
Some buttons are not visible

### ISSUE THREAD

**Issue by skabashnyuk** [mickaelistria/che-editor-eclipseide#1]
Not able to see or click ok button. Not able to resize properly window.
![13 28 11](https://user-images.githubusercontent.com/1614429/50217681-083f8580-0392-11e9-9e16-f54878ac11df.png)
![13 27 57](https://user-images.githubusercontent.com/1614429/50217685-0aa1df80-0392-11e9-8e66-30e6aa7a5e8a.png)

**Comment by skabashnyuk** [comment]
@benoitf FYI

**Comment by benoitf** [comment]
https://github.com/ws-skeleton/eclipse-broadway/issues/2

**Comment by skabashnyuk** [comment]
oops

**Comment by benoitf** [comment]
Better to have duplicates than no report ! :-)

**Comment by mickaelistria** [comment]
> Better to have duplicates than no report ! :-)

Even better: better to have the report in several places to keep track of what to change/test.
The bug is IMO still valid in this repo, https://github.com/ws-skeleton/eclipse-broadway/issues/2 is the cause more than a duplicate. So I'll re-open this bug to keep track of it, and when https://github.com/ws-skeleton/eclipse-broadway/issues/2 is fixed, we'll test it and close here when we see it works in Che.

@skabashnyuk At the moment, our Eclipse team doesn't plan nor have good enough Broadway/Docker skills to work on the eclipse-broadway issues. It's very likely that no effort will come from our side until there is some user/customer pressure for it (which is low probability). But if you're interested in improving the eclipse-broadway image, that would be very welcome!
